#!/usr/bin/env bash

# Function to print subdomain info
print_info() {
    local domain=$1
    local sub=$2

    record=$(dig +short "$sub.$domain" | head -n1)
    record_type=$(dig "$sub.$domain" | awk '/IN/ {print $4; exit}')

    echo "The subdomain $sub is a $record_type record and points to $record"
}

domain=$1

if [ "$#" -eq 2 ]; then
    subdomains=("$2")
else
    subdomains=("www" "lb-01" "web-01" "web-02")
fi

for sub in "${subdomains[@]}"; do
    print_info "$domain" "$sub"
done
